I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/story scripts/ch1.1-5.rpy", line 393, in script
    $ zOpen = false
  File "game/story scripts/ch1.1-5.rpy", line 393, in <module>
    $ zOpen = false
NameError: name 'false' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/story scripts/ch1.1-5.rpy", line 393, in script
    $ zOpen = false
  File "renpy/ast.py", line 922, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "renpy/python.py", line 2218, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/story scripts/ch1.1-5.rpy", line 393, in <module>
    $ zOpen = false
NameError: name 'false' is not defined

Windows-10-10.0.19041
Ren'Py 7.4.4.1439
Song of Glass 1.1
Wed Oct 27 23:04:43 2021
